export default {
  common: {
    ok: "OK",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    reset: "Reset",
    confirm: "Confirm",
    apply: "Apply",
    minutes: "minutes",
  },

  tabs: {
    home: "Home",
    notes: "Notes",
    stats: "Statistics",
    settings: "Settings",
  },

  home: {
    title: "Home",
    currentShift: "Current Shift",
    noShiftApplied: "No shift applied",
    weekStatus: "Week Status",
    workNotes: "Work Notes",
    resetConfirmTitle: "Reset Status",
    resetConfirmMessage: "Are you sure you want to reset today's work status?",
  },

  button: {
    goToWork: "Go to Work",
    checkIn: "Check In",
    checkOut: "Check Out",
    complete: "Complete",
    completed: "Completed",
  },

  workStatus: {
    fullWork: "Present",
    missingAction: "Partial",
    leave: "Leave",
    sick: "Sick",
    holiday: "Holiday",
    absent: "Absent",
    lateEarly: "Late/Early",
    checkIn: "Check in",
    checkOut: "Check out",
  },

  settings: {
    title: "Settings",
    workShifts: "Work Shifts",
    addShift: "Add Shift",
    editShift: "Edit Shift",
    noShifts: "No shifts available",
    viewAllShifts: "View all shifts",
    apply: "Apply",
    applyShiftTitle: "Apply Shift",
    applyShiftMessage: "Are you sure you want to apply this shift?",
    deleteShiftTitle: "Delete Shift",
    deleteShiftMessage: "Are you sure you want to delete this shift?",
    generalSettings: "General Settings",
    darkMode: "Dark Mode",
    language: "Language",
    notificationSound: "Notification Sound",
    vibration: "Vibration",
    simpleButtonMode: "Simple Button Mode",
    simpleButtonModeDesc: "Only show Go to Work button",
  },

  notes: {
    title: "Notes",
    addNote: "Add Note",
    editNote: "Edit Note",
    noNotes: "No notes available",
    noSearchResults: "No notes found",
    search: "Search notes...",
    untitledNote: "Untitled Note",
    deleteNote: "Delete Note",
    deleteNoteTitle: "Delete Note",
    deleteNoteMessage: "Are you sure you want to delete this note?",
    titlePlaceholder: "Note title",
    contentPlaceholder: "Note content...",
    reminderTime: "Reminder Time",
    linkToShifts: "Link to Work Shifts",
    reminderDays: "Reminder Days",
    noShifts: "No work shifts available",
    allDays: "All Days",
    weekdays: "Weekdays",
    weekend: "Weekend",
    titleRequired: "Title is required",
    titleTooLong: "Title cannot exceed 100 characters",
    contentRequired: "Content is required",
    contentTooLong: "Content cannot exceed 300 characters",
    daysRequired: "Please select at least one day",
    error: "Error",
    errorLoading: "Could not load note",
    errorSaving: "Could not save note",
    errorDeleting: "Could not delete note",
  },

  stats: {
    title: "Statistics",
    summary: "Summary",
    calendar: "Calendar",
    export: "Export Report",
    monthlySummary: "Monthly Summary",
    totalWorkDays: "Total Work Days: {count}",
    totalWorkHours: "Total Work Hours",
    averageDaily: "Daily Average",
    legend: "Legend",
  },

  weekdays: {
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    sun: "Sun",
  },
}
