export default {
  common: {
    ok: "OK",
    cancel: "Hủy",
    save: "Lưu",
    delete: "Xóa",
    edit: "Sửa",
    reset: "Đặt lại",
    confirm: "Xác nhận",
    apply: "Áp dụng",
    minutes: "phút",
  },

  tabs: {
    home: "Trang chủ",
    notes: "Ghi chú",
    stats: "Thống kê",
    settings: "Cài đặt",
  },

  home: {
    title: "Trang chủ",
    currentShift: "Ca làm việc hiện tại",
    noShiftApplied: "Chưa áp dụng ca làm việc",
    weekStatus: "Trạng thái tuần",
    workNotes: "Ghi chú công việc",
    resetConfirmTitle: "Đặt lại trạng thái",
    resetConfirmMessage: "Bạn có chắc chắn muốn đặt lại trạng thái làm việc hôm nay không?",
  },

  button: {
    goToWork: "Đi làm",
    checkIn: "Chấm công vào",
    checkOut: "Chấm công ra",
    complete: "Hoàn tất",
    completed: "Đã hoàn tất",
  },

  workStatus: {
    fullWork: "Đủ công",
    missingAction: "Thiếu chấm công",
    leave: "Nghỉ phép",
    sick: "Nghỉ bệnh",
    holiday: "Nghỉ lễ",
    absent: "Vắng mặt",
    lateEarly: "Đi muộn/về sớm",
    checkIn: "Giờ vào",
    checkOut: "Giờ ra",
  },

  settings: {
    title: "Cài đặt",
    workShifts: "Ca làm việc",
    addShift: "Thêm ca làm việc",
    editShift: "Chỉnh sửa ca làm việc",
    noShifts: "Chưa có ca làm việc nào",
    viewAllShifts: "Xem tất cả ca làm việc",
    apply: "Áp dụng",
    applyShiftTitle: "Áp dụng ca làm việc",
    applyShiftMessage: "Bạn có chắc chắn muốn áp dụng ca làm việc này không?",
    deleteShiftTitle: "Xóa ca làm việc",
    deleteShiftMessage: "Bạn có chắc chắn muốn xóa ca làm việc này không?",
    generalSettings: "Cài đặt chung",
    darkMode: "Chế độ tối",
    language: "Ngôn ngữ",
    notificationSound: "Âm thanh thông báo",
    vibration: "Rung khi thông báo",
    simpleButtonMode: "Chế độ nút đơn giản",
    simpleButtonModeDesc: "Chỉ hiển thị nút Đi làm",
  },

  notes: {
    title: "Ghi chú",
    addNote: "Thêm ghi chú",
    editNote: "Chỉnh sửa ghi chú",
    noNotes: "Chưa có ghi chú nào",
    noSearchResults: "Không tìm thấy ghi chú nào",
    search: "Tìm kiếm ghi chú...",
    untitledNote: "Ghi chú không tiêu đề",
    deleteNote: "Xóa ghi chú",
    deleteNoteTitle: "Xóa ghi chú",
    deleteNoteMessage: "Bạn có chắc chắn muốn xóa ghi chú này không?",
    titlePlaceholder: "Tiêu đề ghi chú",
    contentPlaceholder: "Nội dung ghi chú...",
    reminderTime: "Thời gian nhắc nhở",
    linkToShifts: "Liên kết với ca làm việc",
    reminderDays: "Ngày nhắc nhở",
    noShifts: "Chưa có ca làm việc nào",
    allDays: "Tất cả các ngày",
    weekdays: "Ngày trong tuần",
    weekend: "Cuối tuần",
    titleRequired: "Tiêu đề không được để trống",
    titleTooLong: "Tiêu đề không được quá 100 ký tự",
    contentRequired: "Nội dung không được để trống",
    contentTooLong: "Nội dung không được quá 300 ký tự",
    daysRequired: "Vui lòng chọn ít nhất một ngày",
    error: "Lỗi",
    errorLoading: "Không thể tải ghi chú",
    errorSaving: "Không thể lưu ghi chú",
    errorDeleting: "Không thể xóa ghi chú",
  },

  stats: {
    title: "Thống kê",
    summary: "Tổng quan",
    calendar: "Lịch",
    export: "Xuất báo cáo",
    monthlySummary: "Tổng kết tháng",
    totalWorkDays: "Tổng số ngày làm việc: {count}",
    totalWorkHours: "Tổng số giờ làm việc",
    averageDaily: "Trung bình mỗi ngày",
    legend: "Chú thích",
  },

  weekdays: {
    mon: "T2",
    tue: "T3",
    wed: "T4",
    thu: "T5",
    fri: "T6",
    sat: "T7",
    sun: "CN",
  },
}
